### ISSUE TITLE
how to scale?

### ISSUE THREAD

**Issue by SC-Duan** [QuentinRougemont/DemographicInference#1]
Dear,
    I used the SC model to get the params: nu1, nu2, m12, m21, Ts, Tsc = 0.026,0.082,19.49,13.56,10.0,0.09, and the theta=1200, and I don't know how to get the ancestral population (equal to theta or =theta/4/μ ?), and the number of  nu1 and nu2 (0.026,0.082) were really 	 effective size after split? or I should scale? Can you give me some help?
   Thank you very much!

**Comment by QuentinRougemont** [comment]
Hello,
in dadi, theta is equal = 4*Nref*µ, This will give you the size of the Reference population but, you need to know the total length (L) of the locus considered so that  Nref= theta/(4*L*µ).
Be aware that µ may be difficult to estimates depending on the species you are working on.
All elements are expressed in coalescent units, so you also need to convert nu1 and nu2 accordingly.
Similarly, Time is in units of 2Nref generations and nedd to be converted.
Migration rates M is equal to 2Nrefmij and needs to be scaled.
 
Best Regards,
Quentin
 
 
 
 
> Message du 21/12/16 04:38
> De : "dzaccook" 
> A : "QuentinRougemont/DemographicInference" 
> Copie à : "Subscribed" 
> Objet : [QuentinRougemont/DemographicInference] how to scale? (#1)
> 
>
> Dear,
> I used the SC model to get the params: nu1, nu2, m12, m21, Ts, Tsc = 0.026,0.082,19.49,13.56,10.0,0.09, and the theta=1200, and I don't know how to get the ancestral population (equal to theta or =theta/4/μ ?), and the number of nu1 and nu2 (0.026,0.082) were really effective size after split? or I should scale? Can you give me some help?
> Thank you very much!
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/QuentinRougemont/DemographicInference","title":"QuentinRougemont/DemographicInference","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/QuentinRougemont/DemographicInference"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"how to scale? (#1)"}],"action":{"name":"View Issue","url":"https://github.com/QuentinRougemont/DemographicInference/issues/1"}}}

**Comment by SC-Duan** [comment]
Hello,
Thank you for your prompt reply. 
Best wishes,
